apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-rc
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-t
      labels:
        app: nginx
        ver: 1.1
    spec:
      containers:
        - name: nginx-c
          image: nginx
          ports:
            - containerPort: 80
