apiVersion: extensions/vibetal
kind: Deployment
metadata:
  name: openmrs-deploy
spec:
    replicas: 3
    minReadySeconds: 30
    strategy:
        type: RollingUpdate
        rollinguodate:
            maxunavailable: 1
            macsurge: 1
    template:
        metadata:
            labels:
                app: openmrs
        spec:
            containers:
                -   name: openmrs
                    image: rhelwatkar/openmrs
                    ports:
                        -   containerPort: 8080
